"""empty message

Revision ID: 3cd5d948fa2f
Revises: 1f3d85233062
Create Date: 2015-01-10 02:35:52.962902

"""

# revision identifiers, used by Alembic.
revision = '3cd5d948fa2f'
down_revision = '1f3d85233062'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
