"""empty message

Revision ID: c36aaf9d57
Revises: 3cd5d948fa2f
Create Date: 2015-01-12 22:23:58.678229

"""

# revision identifiers, used by Alembic.
revision = 'c36aaf9d57'
down_revision = '3cd5d948fa2f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
